# Generated by Django 4.2.1 on 2023-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branchmetric_calculation_time'),
        ('scraper', '0002_status_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scraper',
            field=models.ManyToManyField(to='scraper.scraperclient'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_branch',
            field=models.ManyToManyField(to='branch.branchmodel'),
        ),
    ]
