# Generated by Django 4.2.1 on 2023-07-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branchmetric_calculation_time'),
        ('scraper', '0003_task_scraper_task_target_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scraper',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='target_branch',
        ),
        migrations.AddField(
            model_name='task',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.scraperclient'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.status'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branchmodel'),
        ),
    ]
