# Generated by Django 5.1.2 on 2024-11-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_task_scraper_remove_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
