# Generated by Django 4.2.1 on 2023-06-30 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0004_delete_commentpool'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.TextField()),
                ('is_trained', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(to='comment.commentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AIManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('trained_structure', models.FilePathField(allow_files=['.sav'], path='/.trained_data')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.commentpool')),
            ],
        ),
    ]
