# Generated by Django 4.2.1 on 2023-07-11 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPool',
            fields=[
                ('last_update', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_trained', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(to='comment.commentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AIManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.commentpool')),
            ],
        ),
    ]
