# Generated by Django 4.2.1 on 2023-07-02 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aimanager_trained_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimanager',
            name='trained_structure',
        ),
        migrations.AlterField(
            model_name='commentpool',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
