# Generated by Django 4.2.1 on 2023-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aimanager_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimanager',
            name='trained_structure',
            field=models.FileField(default=None, null=True, upload_to='.trained_data'),
        ),
    ]
