# Generated by Django 4.2.1 on 2023-06-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_trained', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(to='comment.commentmodel')),
            ],
        ),
    ]
