# Generated by Django 4.2.1 on 2023-07-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_commentmodel_pass_time_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTagColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hex_code', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='commenttag',
            name='sub_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='commenttag',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commenttagcolor'),
        ),
    ]
