# Generated by Django 4.2.1 on 2023-06-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_commentpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpool',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
