# Generated by Django 4.2.1 on 2023-06-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_commentpool_last_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPool',
        ),
    ]
