# Generated by Django 4.2.1 on 2023-07-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_commenttag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttag',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commenttagcolor'),
        ),
    ]
