# Generated by Django 4.2.1 on 2023-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_delete_commentpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttag',
            name='color',
            field=models.TextField(default=None, null=True),
        ),
    ]
