# Generated by Django 4.2.1 on 2023-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_commenttag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='create',
            field=models.DateTimeField(auto_created=True, default=None, null=True),
        ),
    ]
