# Generated by Django 4.2.1 on 2023-06-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_time', models.DateField(auto_created=True)),
                ('sincere_count', models.IntegerField(default=0)),
                ('reputable_count', models.IntegerField(default=0)),
                ('powerful_count', models.IntegerField(default=0)),
                ('competence_count', models.IntegerField(default=0)),
                ('excitement_count', models.IntegerField(default=0)),
                ('repetitive_words', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('explanation', models.TextField(null=True)),
                ('metric', models.ManyToManyField(blank=True, to='branch.branchmetric')),
            ],
        ),
    ]
