# Generated by Django 4.2.1 on 2023-07-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmetric',
            name='negative_count',
            field=models.IntegerField(default=0),
        ),
    ]
