# Generated by Django 4.2.1 on 2023-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branchmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='url',
            field=models.TextField(default=None),
        ),
    ]
