# Generated by Django 4.2.1 on 2023-07-20 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branchmetric_calculation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmetric',
            name='calculation_time',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
