# Generated by Django 4.2.1 on 2023-07-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branchmetric_calculation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmetric',
            name='calculation_time',
            field=models.DateField(auto_now=True),
        ),
    ]
